CREATE TABLE Assembly
(
	Id INTEGER PRIMARY KEY NOT NULL,
	Name TEXT NOT NULL,
	FullName TEXT NOT NULL,
	Version TEXT NOT NULL,
	Culture TEXT NULL,
	PublicKeyToken TEXT NULL,
	MainModuleId INTEGER NULL REFERENCES Module,
	ModuleCount INTEGER NOT NULL,
	ResourceCount INTEGER NOT NULL,
	TypeCount INTEGER NOT NULL,
	MethodCount INTEGER NOT NULL
);

CREATE TABLE Module
(
	Id INTEGER PRIMARY KEY NOT NULL,
	AssemblyId INTEGER NOT NULL REFERENCES Assembly,
	Name TEXT NOT NULL,
	FullPath TEXT NOT NULL,
	ModuleType TEXT NOT NULL,
	TargetRuntimeVersion TEXT NOT NULL,
	TargetPlatform TEXT NOT NULL,
	ContainsNativeCode BOOLEAN NOT NULL,
	IsStrongNameSigned BOOLEAN NOT NULL,
	EntryPointMethodId INTEGER NULL REFERENCES Method,
	ResourceCount INTEGER NOT NULL,
	TypeCount INTEGER NOT NULL,
	MethodCount INTEGER NOT NULL
);

CREATE TABLE Type
(
	Id INTEGER PRIMARY KEY NOT NULL,
	AssemblyId INTEGER NOT NULL REFERENCES Assembly,
	ModuleId INTEGER NOT NULL REFERENCES Module,
	Name TEXT NOT NULL,
	FullName TEXT NOT NULL,
	FullReferenceName TEXT NOT NULL,
	Namespace TEXT NULL,
	MethodCount INTEGER NOT NULL
);

CREATE TABLE TypeReference
(
	Id INTEGER PRIMARY KEY NOT NULL,
	ReferenceName TEXT NOT NULL,
	FullReferenceName TEXT NOT NULL,
	Namespace TEXT NULL
);

CREATE TABLE Method
(
	Id INTEGER PRIMARY KEY NOT NULL,
	AssemblyId INTEGER NOT NULL REFERENCES Assembly,
	ModuleId INTEGER NOT NULL REFERENCES Module,
	TypeId INTEGER NOT NULL REFERENCES Type,
	Name TEXT NOT NULL,
	FullName TEXT NOT NULL,
	ReturnType TEXT NOT NULL,
	FullReturnType TEXT NOT NULL
);

CREATE TABLE Instruction
(
	Id INTEGER PRIMARY KEY NOT NULL,
	AssemblyId INTEGER NOT NULL REFERENCES Assembly,
	ModuleId INTEGER NOT NULL REFERENCES Module,
	TypeId INTEGER NOT NULL REFERENCES Type,
	MethodId INTEGER NOT NULL REFERENCES Method,
	Value TEXT NOT NULL
);

CREATE TABLE Resource
(
	Id INTEGER PRIMARY KEY NOT NULL,
	AssemblyId INTEGER NOT NULL REFERENCES Assembly,
	ModuleId INTEGER NOT NULL REFERENCES Module,
	Name TEXT NOT NULL,
	ResourceType TEXT NOT NULL,
	IsPublic BOOLEAN NOT NULL
);

CREATE TABLE Attribute
(
	Id INTEGER PRIMARY KEY NOT NULL,
	AssemblyId INTEGER NULL REFERENCES Assembly,
	ModuleId INTEGER NULL REFERENCES Module,
	Name TEXT NOT NULL,
	FullName TEXT NOT NULL,
	AttributeType TEXT NOT NULL
);